# Generated by Django 4.2.30 on 2026-08-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sub_department',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
