# Generated by Django 4.2.30 on 2026-08-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_department_sub_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='sub_department',
        ),
    ]
