# Generated by Django 4.2.30 on 2026-08-12 05:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_department_sub_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='sub-department-icons')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('priority', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.TextField(blank=True, null=True)),
                ('meta_keyword', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_departments', to='core.department')),
            ],
        ),
    ]
