# Generated by Django 4.2.30 on 2026-08-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdepartment',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='sub-departments'),
        ),
        migrations.AddField(
            model_name='subdepartment',
            name='breadcamp',
            field=models.FileField(blank=True, null=True, upload_to='sub-department-banners'),
        ),
    ]
