# Generated by Django 4.2.30 on 2026-08-31 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customerprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
    ]
